ES_WEBKYSO/Areas/CauHinh/Controllers/CauHinhBoPhanKyController.cs
using Common.Helpers;
using ES_WEBKYSO.Areas.CauHinh.Models;
using ES_WEBKYSO.Common;
using ES_WEBKYSO.Controllers;
using ES_WEBKYSO.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ES_WEBKYSO.Areas.CauHinh.Controllers
{
    public class CauHinhBoPhanKyController : BaseController
    {
        Result result = new Result();
        public ActionResult Index()
        {
            ViewBag.MA_DVIQLY = new CommonUserProfile().MA_DVIQLY;
            // truyền giá trị sang dropdownlist
            string madonvi = ViewBag.MA_DVIQLY.ToString();
            var listBangKe = Uow.RepoBase<CFG_BANGKE_DONVI>().GetAll()
               .Join(Uow.RepoBase<D_LOAI_BANGKE>().GetAll(),
                  o => o.MA_LOAIBANGKE,
                  d => d.MA_LOAIBANGKE,
                  (o, d) => new {
                      MA_LOAIBANGKE = o.MA_LOAIBANGKE,
                      TEN_LOAIBANGKE = d.TEN_LOAIBANGKE,
                      MA_DVIQLY = o.MA_DVIQLY
                  }
               ).Where(m => m.MA_DVIQLY == madonvi)
               .ToList();
            if(TempData["MA_LOAI_BKE_DVI"] == null)
            {
                ViewData["MA_LOAI_BKE_DVI"] = listBangKe.Select(x => new SelectListItem
                {
                    Value = x.MA_LOAIBANGKE,
                    Text = x.TEN_LOAIBANGKE,
                    Selected = x.MA_LOAIBANGKE == "BKCS" ? true : false
                }).ToList();
            }
           else
            {
                ViewData["MA_LOAI_BKE_DVI"] = TempData["MA_LOAI_BKE_DVI"];
            }
            return View();
        }
        [HttpPost]
        public ActionResult GetJson(BOPHANKY boPhanKy)
        {
            var paging = Request.Params.ToPaging("ID");
            // Lấy dữ liệu từ CSDL sử dụng Paging để phân trang
            var data = Uow.RepoBase<CFG_BOPHAN_KY>().ManagerGetAllForIndex(boPhanKy, paging.OrderKey, ref paging).ToList();
            paging.data = data;
            return Json(paging, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            ViewBag.MA_DVIQLY = new CommonUserProfile().MA_DVIQLY;
            string madonvi = ViewBag.MA_DVIQLY.ToString();
            var listBangKe = Uow.RepoBase<CFG_BANGKE_DONVI>().GetAll()
                .Join(Uow.RepoBase<D_LOAI_BANGKE>().GetAll(),
                   o => o.MA_LOAIBANGKE,
                   d => d.MA_LOAIBANGKE,
                   (o, d) => new {
                       MA_LOAIBANGKE = o.MA_LOAIBANGKE,
                       TEN_LOAIBANGKE = d.TEN_LOAIBANGKE,
                       MA_DVIQLY = o.MA_DVIQLY
                   }
                ).Where(m => m.MA_DVIQLY == madonvi)
                .ToList();
            var listBoPhanKy = Uow.RepoBase<WebpagesRoles>().GetAll().ToList();
            ViewData["MA_LOAI_BKE_DVI"] = listBangKe.Select(x => new SelectListItem
            {
                Value = x.MA_LOAIBANGKE,
                Text = x.TEN_LOAIBANGKE
            }).ToList();
            ViewData["MA_BO_PHAN_KY"] = listBoPhanKy.Select(x => new SelectListItem
            {
                Value = x.RoleId.ToString(),
                Text = x.RoleName.ToString()
            }).ToList();
            int size = listBoPhanKy.Count();
            List<SelectListItem> list_item = new List<SelectListItem>();
            for (int i = 1; i <= size; i++)
            {
                SelectListItem item = new SelectListItem();
                item.Value = i.ToString();
                item.Text = i.ToString();
                list_item.Add(item);
            }
            ViewData["THUTU_KY"] = list_item.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(CFG_BOPHAN_KY model)
        {
            if (ModelState.IsValid)
            {
                string madonvi = model.MA_DVIQLY.ToString();
                var listBangKe = Uow.RepoBase<CFG_BANGKE_DONVI>().GetAll()
                    .Join(Uow.RepoBase<D_LOAI_BANGKE>().GetAll(),
                       o => o.MA_LOAIBANGKE,
                       d => d.MA_LOAIBANGKE,
                       (o, d) => new {
                           MA_LOAIBANGKE = o.MA_LOAIBANGKE,
                           TEN_LOAIBANGKE = d.TEN_LOAIBANGKE,
                           MA_DVIQLY = o.MA_DVIQLY
                       }
                    ).Where(m => m.MA_DVIQLY == madonvi)
                    .ToList();
                TempData["MA_LOAI_BKE_DVI"] = listBangKe.Select(x => new SelectListItem
                {
                    Value = x.MA_LOAIBANGKE,
                    Text = x.TEN_LOAIBANGKE,
                    Selected = x.MA_LOAIBANGKE == model.MA_LOAIBANGKE ? true : false
                }).ToList();
                var modelOrig = Uow.RepoBase<CFG_BOPHAN_KY>().GetOne(x => x.MA_DVIQLY == model.MA_DVIQLY && x.MA_LOAIBANGKE == model.MA_LOAIBANGKE && x.RoleId == model.RoleId);
                if (modelOrig != null)
                {
                    TempData["Error"] = "Thêm bộ phận ký không thành công vì bộ phận đã tồn tại";
                    return Redirect("/CauHinh/CauHinhBoPhanKy");

                }

                int kq = Uow.RepoBase<CFG_BOPHAN_KY>().Create(model);

                if (kq == 1)
                {
                    TempData["Success"] = "Thêm thành công bộ phận ký";
                    return Redirect("/CauHinh/CauHinhBoPhanKy");

                }
                else
                {
                    TempData["Error"] = "Thêm bộ phận ký thất bại";
                    return Redirect("/CauHinh/CauHinhBoPhanKy");

                }

            }
            else
            {
                TempData["Error"] = "Xảy ra lỗi: thiếu dữ liệu ";
                return Redirect("/CauHinh/CauHinhBoPhanKy");

            }
        }

        public ActionResult Update(int ID)
        {
            ViewBag.MA_DVIQLY = new CommonUserProfile().MA_DVIQLY;
            ViewBag.Title = "Sửa thông tin bộ phận ký";
            var model = Uow.RepoBase<CFG_BOPHAN_KY>().GetOne(ID);
            // truyền giá trị sang dropdownlist
            string madonvi = ViewBag.MA_DVIQLY.ToString();
            var listBangKe = Uow.RepoBase<CFG_BANGKE_DONVI>().GetAll()
               .Join(Uow.RepoBase<D_LOAI_BANGKE>().GetAll(),
                  o => o.MA_LOAIBANGKE,
                  d => d.MA_LOAIBANGKE,
                  (o, d) => new {
                      MA_LOAIBANGKE = o.MA_LOAIBANGKE,
                      TEN_LOAIBANGKE = d.TEN_LOAIBANGKE,
                      MA_DVIQLY = o.MA_DVIQLY
                  }
               ).Where(m => m.MA_DVIQLY == madonvi)
               .ToList();
            var listBoPhanKy = Uow.RepoBase<WebpagesRoles>().GetAll().ToList();
            ViewData["MA_LOAI_BKE_DVI"] = listBangKe.Select(x => new SelectListItem
            {
                Value = x.MA_LOAIBANGKE,
                Text = x.TEN_LOAIBANGKE,
                Selected = x.MA_LOAIBANGKE == model.MA_LOAIBANGKE ? true : false
            }).ToList();

            ViewData["MA_BO_PHAN_KY"] = listBoPhanKy.Select(x => new SelectListItem
            {
                Value = x.RoleId.ToString(),
                Text = x.RoleName.ToString(),
                Selected = x.RoleId == model.RoleId ? true : false
            }).ToList();
            int size = listBoPhanKy.Count();
            List<SelectListItem> list_item = new List<SelectListItem>();
            for (int i = 1; i <= size; i++)
            {
                SelectListItem item = new SelectListItem();
                item.Value = i.ToString();
                item.Text = i.ToString();
                list_item.Add(item);
            }
            foreach (var item in list_item)
            {
                if (item.Value == model.THU_TUKY.ToString())
                    item.Selected = true;
                else
                    item.Selected = false;
            }
            ViewData["THUTU_KY"] = list_item.ToList();

            if (model == null)
            {
                result.Status = false;
                result.Message = "Xảy ra lỗi: Không tìm thấy bản ghi";
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(CFG_BOPHAN_KY model)
        {
            ViewBag.Title = "Cập nhật thông tin thông tin ký bảng kê";
            var listBangKe = Uow.RepoBase<CFG_BANGKE_DONVI>().GetAll()
                .Join(Uow.RepoBase<D_LOAI_BANGKE>().GetAll(),
                   o => o.MA_LOAIBANGKE,
                   d => d.MA_LOAIBANGKE,
                   (o, d) => new {
                       MA_LOAIBANGKE = o.MA_LOAIBANGKE,
                       TEN_LOAIBANGKE = d.TEN_LOAIBANGKE,
                       MA_DVIQLY = o.MA_DVIQLY
                   }
                ).Where(m => m.MA_DVIQLY == model.MA_DVIQLY)
                .ToList();
            TempData["MA_LOAI_BKE_DVI"] = listBangKe.Select(x => new SelectListItem
            {
                Value = x.MA_LOAIBANGKE,
                Text = x.TEN_LOAIBANGKE,
                Selected = x.MA_LOAIBANGKE == model.MA_LOAIBANGKE ? true : false
            }).ToList();
            var modelOrig = Uow.RepoBase<CFG_BOPHAN_KY>().GetOne(x => x.MA_DVIQLY == model.MA_DVIQLY && x.MA_LOAIBANGKE == model.MA_LOAIBANGKE && x.RoleId == model.RoleId && x.THU_TUKY == model.THU_TUKY && x.MO_TA == model.MO_TA);
            if (modelOrig != null)
            {
                TempData["Error"] = "Sửa không thành công vì ký bảng kê đã tồn tại";
                return Redirect("/CauHinh/CauHinhBoPhanKy");
            }
           
            int kq = Uow.RepoBase<CFG_BOPHAN_KY>().Update(model);

            if (kq == 1)
            {
                TempData["Success"] = "Sửa thành công ký bảng kê";
                return Redirect("/CauHinh/CauHinhBoPhanKy");
            }

ES_WEBKYSO/Areas/CauHinh/Views/CauHinhBoPhanKy/Create.cshtml
@model ES_WEBKYSO.Models.CFG_BOPHAN_KY


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">@ViewBag.Title</h4>
</div>
@using (Html.BeginForm("Create", "CauHinhBoPhanKy", FormMethod.Post, new { @class = "form-horizontal", name = "frm", id = "frm" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.EditorFor(x => x.MA_DVIQLY, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @Value = ViewBag.MA_DVIQLY } })

            @Html.EditorFor(x => x.MA_LOAIBANGKE, new { dropKey = "MA_LOAI_BKE_DVI", label = "--- Chọn bảng kê ---", htmlAttributes = new { @class = "form-control "  } })
        </div>
        <div class="form-group">
            @Html.EditorFor(x => x.RoleId, new { dropKey = "MA_BO_PHAN_KY", label = "--- Chọn bộ phận ký ---", htmlAttributes = new { @class = "form-control " } })

            @Html.EditorFor(x => x.THU_TUKY, new { dropKey = "THUTU_KY", label = "--- Chọn thứ tự ký ---", htmlAttributes = new { @class = "form-control " } })
        </div>
        <div style="margin-left:15px;">
            <div class="form-group">
                <label> Ghi chú </label>
            </div>
            <div class="form-group">
                @Html.TextAreaFor(x => x.MO_TA, 5, 120, htmlAttributes: new { style = "width: 100%; max-width: 100%;" })
            </div>
        </div>
    </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary" id="BangKeCreate">Cập nhật</button>
            <button type="button" class="btn btn-default" data-dismiss="modal" id="">Đóng</button>
        </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $.validator.unobtrusive.parse("#frm");

        function Create() {
            var bophanky = [];
            bophanky.MA_DVIQLY = $("#MA_DVIQLY").val();
            bophanky.MA_LOAIBANGKE = $("#MA_LOAIBANGKE").val();
            bophanky.RoleId = $("#RoleId").val();
            bophanky.THU_TUKY = $("#THU_TUKY").val();
            bophanky.MO_TA = $("#MO_TA").val();
            $.ajax({
                type: 'POST',
                cache: false,
                async: true,
                url: "/CauHinh/CauHinhBoPhanKy/Create",
                dataType: 'json',
                data: JSON.stringify({ model: bophanky }),
                contentType: "application/json; charset=utf-8",
                success: function (result) {
                    if (result.success == true) {
                        alert(result.message);
                        grid.ajax.reload();
                    } else {
                        alert(result.message);
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert(result.message);
                },
                complete: function (result) {
                    grid.ajax.reload();
                }
            });
        }
        
    });
</script>

@section PageScripts{
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

ES_WEBKYSO/Areas/CauHinh/Views/CauHinhBoPhanKy/Index.cshtml
@model ES_WEBKYSO.Models.CFG_BOPHAN_KY
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container" style="min-height: 851px;">
    <div class="row">
        <div class="col-sm-12">
            <div class="page-header">
                <h3>@*<span class="page-header-text">@ViewBag.Title</span>*@</h3>
                <h3><span style="color: teal">Cấu hình bộ phận ký </span></h3>
            </div>
        </div>
    </div>
    @*thông báo*@
    <div class="col-sm-12" align="left">
        @Html.ValidationSummary()
        @if (TempData["Error"] != null)
            {
            
            <div class="alert alert-danger">
                <button data-dismiss="alert" class="close">
                    ×
                </button>
                <i class="fa fa-times-circle"></i>
                <strong>Error!</strong> @TempData["Error"].ToString()
            </div>
        }
        @if (TempData["Success"] != null)
            {
            <div class="alert alert-success">
                <button data-dismiss="alert" class="close">
                    ×
                </button>
                <i class="fa fa-check-circle"></i>
                <strong>Success!</strong> @TempData["Success"].ToString()
            </div>
        }
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-success">
                <div class="panel-heading">
                    Tìm kiếm
                    <i class="fa fa-search text-right"></i>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <fieldset>
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-10">
                                            <div class="form-group">
                                                @Html.EditorFor(x => x.MA_DVIQLY, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @Value = ViewBag.MA_DVIQLY } })

                                                @Html.EditorFor(x => x.MA_LOAIBANGKE, new { dropKey = "MA_LOAI_BKE_DVI", label = "--- Chọn bảng kê ---", htmlAttributes = new { @class = "form-control " } })
                                            </div>
                                        </div>
                                        <div class="col-md-2">
                                            <button type="submit" class="btn btn-primary" id="btnGetData" style="margin-top:25px;">
                                                <i class="fa fa-search"></i>
                                                Tìm kiếm
                                            </button>
                                        </div>
                                    </div>
                                </div>

                            </fieldset>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="clip-list-2"></i>
                    Danh sách ký bảng kê
                    <div class="panel-tools">
                        <a href="@Url.Action("Create")" data-toggle="modal" data-target="#popupStaticModal" class="btn btn-xs tooltips" data-original-title="Thêm">
                            <i class="fa fa-plus"></i>
                        </a>
                        <a class="btn btn-xs btn-link panel-collapse expand"></a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover table-full-width" id="TableGeneric">
                            <thead></thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section PageScripts{
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @Scripts.Render("~/js/datatables")
    <script src="~/Content/themes/ClipOne/plugins/DataTables/media/js/jquery.dataTables.editable.js"></script>

    <script type="text/javascript">


    $(function () {
        $('.form-control :input:first').focus();
        //$('.form-control :input').focus();
    });

    //đổ dự liệu vào data-table có chức năng sửa xóa
    (function ($) {
        "use strict";
        window.TableConfig = [];
        window.TableConfig[0] = {
            id: "TableGeneric",
            url: "@Url.Action("GetJson")",
            reloadFunc: function (d) {
                d.MA_LOAIBANGKE = $("#MA_LOAIBANGKE").val();
                d.MA_DVIQLY = $("#MA_DVIQLY").val();
        },
        AddOn: {
            "columnDefs": [
                {
                    "targets": -1,
                    "data": null,
                    "render": function (data, type, full) {
                        var ret = '<div><a class="btn btn-xs btn-teal tooltips Edit" data-toggle="modal" data-target="#popupStaticModal" data-original-title="Sửa" href="@Url.Action("Update", "CauHinhBoPhanKy", new { ID = "IDParameter" })"><i class="fa fa-edit"></i> Sửa</a>  ' +
                            '<a class="btn btn-xs btn-bricky tooltips Delete" data-id="IDParameter" href="#"><i class="fa fa-trash-o"></i> Xóa</a></div>';
                        ret = ret.replace(/IDParameter/g, data.MA_BOPHAN_KY);
                        return ret;
                    }
                }
            ]
        },
            columns: [
            {
                header: "Mã đơn vị",
                'bSortable': false,
                className: "center",
                data: "MA_DVIQLY"
            },

             {
                 header: "Mã bảng kê",
                 'bSortable': false,
                 className: "center",
                 data: "MA_LOAIBANGKE"
             },
             {
                 header: "Tên bảng kê",
                 'bSortable': false,
                 className: "center",
                 data: "Ten_LoaiBangKe"
             },
             {
                 header: "Tên bộ phận ky",
                 'bSortable': false,
                 className: "center",
                 data: "Ten_BoPhanKy"
             },
             {
                 header: "Thứ tự ký",
                 'bSortable': false,
                 className: "center",
                 data: "THU_TUKY"
             },
            {
                header: "Ghi chú",
                'bSortable': false,
                className: "center",
                data: "MO_TA"
            },
            {
                'bSortable': false,
                header: "Tác vụ",
                className: "center",
                data: null
            }
        ],
        func: function (grid) {
            window.TableGenericCAUHINHGrid = grid;
            $("#TableGeneric")
                .on('click',
                    '.Delete',
                    function (e) {
                        e.preventDefault();
                        var thisTrData = $(this).attr('data-id');

                        if (confirm("Bạn có chắc chắn muốn xóa ?")) {
                            $.ajax({
                                type: 'POST',
                                cache: false,
                                async: true,
                                url: "@Html.Raw(Url.Action("Delete"))",
                                dataType: 'json',
                                data: JSON.stringify({ ID: thisTrData }),
                                contentType: "application/json; charset=utf-8",
                                success: function (result) {
                                    if (result.Status == true) {
                                        alert(result.Message);
                                    } else {
                                        alert(result.Message);
                                    }
                                },
                                error: function (jqXHR, textStatus, errorThrown) {
                                    alert(result.Message);
                                },
                                complete: function (result) {
                                    grid.ajax.reload();
                                }
                            });
                    }

            });
    }
    };
    $("#btnGetData").on('click',
        function () {
            AutoDataTable();
        });
    })(jQuery);


    </script>


}

ES_WEBKYSO/Areas/CauHinh/Views/CauHinhBoPhanKy/Update.cshtml
@model ES_WEBKYSO.Models.CFG_BOPHAN_KY


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">@ViewBag.Title</h4>
</div>
@using (Html.BeginForm("Update", "CauHinhBoPhanKy", FormMethod.Post, new { @class = "form-horizontal", name = "frm", id = "frm" }))
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.HiddenFor(x=>x.MA_BOPHAN_KY)
            @Html.EditorFor(x => x.MA_DVIQLY, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @Value = ViewBag.MA_DVIQLY } })

            @Html.EditorFor(x => x.MA_LOAIBANGKE, new { dropKey = "MA_LOAI_BKE_DVI", label = "--- Chọn bảng kê ---", htmlAttributes = new { @class = "form-control ",
           @readonly = "readonly" @*@disabled = "disabled"*@ } })
        </div>
        <div class="form-group">
            @Html.EditorFor(x => x.RoleId, new { dropKey = "MA_BO_PHAN_KY", label = "--- Chọn bộ phận ký ---", htmlAttributes = new { @class = "form-control " } })

            @Html.EditorFor(x => x.THU_TUKY, new { dropKey = "THUTU_KY", label = "--- Chọn thứ tự ký ---", htmlAttributes = new { @class = "form-control " } })
        </div>
        <div style="margin-left:15px;">
            <div class="form-group">
                <label> Ghi chú </label>
            </div>
            <div class="form-group">
                @Html.TextAreaFor(x => x.MO_TA, 5, 120, htmlAttributes: new { style = "width: 100%; max-width: 100%;" })
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary" id="BangKeCreate" onclick="return checkValue()">Cập nhật</button>
        <button type="button" class="btn btn-default" data-dismiss="modal" id="">Đóng</button>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $.validator.unobtrusive.parse("#frm");
    });
</script>

@section PageScripts{
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}